# Generated by Django 2.2.8 on 2020-03-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PocketGarage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Contraseña',
            field=models.CharField(default='', max_length=25),
        ),
    ]
