# Generated by Django 2.2.8 on 2020-03-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PocketGarage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='CI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='CI',
            field=models.IntegerField(default=0),
        ),
    ]
