# Generated by Django 2.2.8 on 2020-03-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PocketGarage', '0002_usuario_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='Vendedor',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='Propietario',
        ),
        migrations.AddField(
            model_name='repuesto',
            name='Info_Vendedor',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='Info_Propietario',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='CI',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
